[phases.setup]
aptPkgs = ["libgl1", "libglib2.0-0", "libsm6", "libxext6", "libxrender1"]

[phases.install]
cmds = [
  "pip install --no-cache-dir tensorflow==2.13.0 numpy==1.24.3",
  "pip install --no-cache-dir opencv-python-headless==4.8.1.78",
  "pip install --no-cache-dir --no-deps deepface==0.0.79",
  "pip install --no-cache-dir pillow==11.3.0 flask==3.1.2 flask-cors==6.0.1 boto3==1.40.45 tqdm==4.67.1 requests==2.32.5 gunicorn==21.2.0",
  "pip install --no-cache-dir pandas gdown fire"
]

[start]
cmd = "python api.py"
